# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-08 19:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppinggroup',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='shoppinggroup',
            name='updated',
        ),
    ]
