# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-13 09:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='item',
            name='updated',
        ),
        migrations.AddField(
            model_name='item',
            name='is_bought',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='quantity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
