# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-13 10:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_auto_20180113_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='is_bought',
            field=models.BooleanField(default=False),
        ),
    ]
